-- MySQL Script generated by MySQL Workbench
-- 10/27/16 11:55:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema insurance_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema insurance_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `insurance_project` DEFAULT CHARACTER SET utf8 ;
USE `insurance_project` ;

-- -----------------------------------------------------
-- Table `insurance_project`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insurance_project`.`customer` (
  `idcustomer` INT(11) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `cnp` BIGINT(13) NOT NULL,
  `age` INT(11) NOT NULL,
  `adress` LONGTEXT NOT NULL,
  PRIMARY KEY (`idcustomer`),
  UNIQUE INDEX `cnp_UNIQUE` (`cnp` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `insurance_project`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insurance_project`.`employee` (
  `employeeId` INT(11) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `loginId` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `cnp` BIGINT(13) NOT NULL,
  `beginningDate` DATE NOT NULL,
  `employeeType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`employeeId`),
  UNIQUE INDEX `cnp_UNIQUE` (`cnp` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `insurance_project`.`policy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insurance_project`.`policy` (
  `policyId` INT(11) NOT NULL,
  `policyType` VARCHAR(45) NOT NULL,
  `amount` DECIMAL(2,0) NOT NULL,
  `discount` DECIMAL(2,0) NOT NULL,
  `employeeId` INT(11) NOT NULL,
  `customerId` INT(11) NOT NULL,
  PRIMARY KEY (`policyId`),
  INDEX `customerId_idx` (`customerId` ASC),
  INDEX `employeeId_idx` (`employeeId` ASC),
  CONSTRAINT `customerId`
    FOREIGN KEY (`customerId`)
    REFERENCES `insurance_project`.`customer` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `employeeId`
    FOREIGN KEY (`employeeId`)
    REFERENCES `insurance_project`.`employee` (`employeeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `insurance_project`.`claims`
-- -----------------------------------------------------
ALTER TABLE `insurance_project`.`claims`
  DROP FOREIGN KEY `idPolicy`;
ALTER TABLE `insurance_project`.`claims`
  DROP COLUMN `idPolicy`,
  CHANGE COLUMN `idclaims` `id` INT(11) NOT NULL ,
  CHANGE COLUMN `claimsType` `type` VARCHAR(45) NOT NULL ,
  DROP INDEX `idPolicy_idx` , RENAME TO  `insurance_project`.`claim` ;



-- -----------------------------------------------------
-- Table `insurance_project`.`homepolicy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insurance_project`.`homepolicy` (
  `idhomePolicy` INT(11) NOT NULL,
  `homeType` VARCHAR(45) NOT NULL,
  `homeAdress` VARCHAR(45) NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `idCustomerH` INT(11) NOT NULL,
  `idPolicyH` INT(11) NOT NULL,
  PRIMARY KEY (`idhomePolicy`),
  INDEX `idCustomerH_idx` (`idCustomerH` ASC),
  INDEX `idPolicyH_idx` (`idPolicyH` ASC),
  CONSTRAINT `idCustomerH`
    FOREIGN KEY (`idCustomerH`)
    REFERENCES `insurance_project`.`customer` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPolicyH`
    FOREIGN KEY (`idPolicyH`)
    REFERENCES `insurance_project`.`policy` (`policyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `insurance_project`.`lifepolicy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insurance_project`.`lifepolicy` (
  `idlifePolicy` INT(11) NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `idCustomerL` INT(11) NOT NULL,
  `idPolicyL` INT(11) NOT NULL,
  PRIMARY KEY (`idlifePolicy`),
  INDEX `customerIdL_idx` (`idCustomerL` ASC),
  INDEX `idPolicyL_idx` (`idPolicyL` ASC),
  CONSTRAINT `idCustomerL`
    FOREIGN KEY (`idCustomerL`)
    REFERENCES `insurance_project`.`customer` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPolicyL`
    FOREIGN KEY (`idPolicyL`)
    REFERENCES `insurance_project`.`policy` (`policyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `insurance_project`.`rcapolicy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insurance_project`.`rcapolicy` (
  `idrcaPolicy` INT(11) NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `discount` DECIMAL(2,0) NULL DEFAULT NULL,
  `idCustomerR` INT(11) NOT NULL,
  `idPolicyR` INT(11) NOT NULL,
  PRIMARY KEY (`idrcaPolicy`),
  INDEX `idCustomerR_idx` (`idCustomerR` ASC),
  INDEX `idPolicyR_idx` (`idPolicyR` ASC),
  CONSTRAINT `idCustomerR`
    FOREIGN KEY (`idCustomerR`)
    REFERENCES `insurance_project`.`customer` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPolicyR`
    FOREIGN KEY (`idPolicyR`)
    REFERENCES `insurance_project`.`policy` (`policyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `insurance_project`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insurance_project`.`vehicle` (
  `vehicleId` INT(11) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `cilindree` INT(11) NOT NULL,
  `kw` INT(11) NOT NULL,
  `seats` INT(11) NOT NULL,
  `identificationNo` BIGINT(17) NOT NULL,
  `registrationNo` VARCHAR(45) NOT NULL,
  `claimsId` INT(11) NOT NULL,
  `policyId` INT(11) NOT NULL,
  PRIMARY KEY (`vehicleId`),
  UNIQUE INDEX `identificationNo_UNIQUE` (`identificationNo` ASC),
  UNIQUE INDEX `registrationNo_UNIQUE` (`registrationNo` ASC),
  INDEX `policyId_idx` (`policyId` ASC),
  INDEX `claimsId_idx` (`claimsId` ASC),
  CONSTRAINT `policyId`
    FOREIGN KEY (`policyId`)
    REFERENCES `insurance_project`.`policy` (`policyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
