package asigurari.gui;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

/**
 * Created by buresina on 31/10/2016.
 */
public class MainPage {
    private JPanel Welcome;
    private JFormattedTextField insertYourUsernameFormattedTextField;
    private JLabel usernameLabel;
    private JLabel passwordLabel;
    private JFormattedTextField insertYourPasswordFormattedTextField;

    public MainPage() {
        $$$setupUI$$$();
        Welcome.addComponentListener(new ComponentAdapter() {
            @Override
            public int hashCode() {
                return super.hashCode();
            }

            @Override
            public boolean equals(Object o) {
                return super.equals(o);
            }

            @Override
            protected Object clone() throws CloneNotSupportedException {
                return super.clone();
            }

            @Override
            public String toString() {
                return super.toString();
            }

            @Override
            protected void finalize() throws Throwable {
                super.finalize();
            }

            @Override
            public void componentResized(ComponentEvent componentEvent) {
                super.componentResized(componentEvent);
            }

            @Override
            public void componentMoved(ComponentEvent componentEvent) {
                super.componentMoved(componentEvent);
            }

            @Override
            public void componentShown(ComponentEvent componentEvent) {
                super.componentShown(componentEvent);
            }

            @Override
            public void componentHidden(ComponentEvent componentEvent) {
                super.componentHidden(componentEvent);
            }
        });
    }

    private void createUIComponents() {

        // TODO: place custom component creation code here
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        Welcome = new JPanel();
        Welcome.setLayout(new FormLayout("fill:d:grow", "center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        Welcome.setBackground(new Color(-8223857));
        Welcome.setDoubleBuffered(false);
        Welcome.setFont(new Font(Welcome.getFont().getName(), Font.BOLD, Welcome.getFont().getSize()));
        Welcome.setForeground(new Color(-8223857));
        Welcome.setName("passwordText");
        usernameLabel = new JLabel();
        usernameLabel.setAutoscrolls(false);
        usernameLabel.setBackground(new Color(-15789035));
        usernameLabel.setDoubleBuffered(false);
        usernameLabel.setFocusTraversalPolicyProvider(false);
        usernameLabel.setFont(new Font(usernameLabel.getFont().getName(), Font.BOLD, usernameLabel.getFont().getSize()));
        usernameLabel.setForeground(new Color(-14932698));
        usernameLabel.setHorizontalAlignment(0);
        usernameLabel.setHorizontalTextPosition(0);
        usernameLabel.setIconTextGap(30);
        usernameLabel.setInheritsPopupMenu(false);
        usernameLabel.setMaximumSize(new Dimension(10000, 50000));
        usernameLabel.setName("usernameLabel");
        usernameLabel.setPreferredSize(new Dimension(400, 40));
        usernameLabel.setText("Username");
        usernameLabel.putClientProperty("html.disable", Boolean.FALSE);
        CellConstraints cc = new CellConstraints();
        Welcome.add(usernameLabel, new CellConstraints(1, 1, 1, 1, CellConstraints.CENTER, CellConstraints.DEFAULT, new Insets(1, 1, 1, 1)));
        insertYourUsernameFormattedTextField = new JFormattedTextField();
        insertYourUsernameFormattedTextField.setAlignmentX(1.0f);
        insertYourUsernameFormattedTextField.setAlignmentY(1.0f);
        insertYourUsernameFormattedTextField.setBackground(new Color(-919817));
        insertYourUsernameFormattedTextField.setCaretColor(new Color(-1904652));
        insertYourUsernameFormattedTextField.setCaretPosition(20);
        insertYourUsernameFormattedTextField.setDisabledTextColor(new Color(-14932698));
        insertYourUsernameFormattedTextField.setDragEnabled(true);
        insertYourUsernameFormattedTextField.setEditable(true);
        insertYourUsernameFormattedTextField.setFont(new Font(insertYourUsernameFormattedTextField.getFont().getName(), Font.PLAIN, insertYourUsernameFormattedTextField.getFont().getSize()));
        insertYourUsernameFormattedTextField.setForeground(new Color(-3946295));
        insertYourUsernameFormattedTextField.setHorizontalAlignment(0);
        insertYourUsernameFormattedTextField.setMargin(new Insets(1, 1, 1, 1));
        insertYourUsernameFormattedTextField.setName("userNameText");
        insertYourUsernameFormattedTextField.setOpaque(true);
        insertYourUsernameFormattedTextField.setPreferredSize(new Dimension(300, 40));
        insertYourUsernameFormattedTextField.setRequestFocusEnabled(false);
        insertYourUsernameFormattedTextField.setSelectedTextColor(new Color(-723724));
        insertYourUsernameFormattedTextField.setSelectionColor(new Color(-1510154));
        insertYourUsernameFormattedTextField.setText("insert your username");
        Welcome.add(insertYourUsernameFormattedTextField, new CellConstraints(1, 3, 1, 1, CellConstraints.CENTER, CellConstraints.DEFAULT, new Insets(1, 1, 1, 1)));
        passwordLabel.setAlignmentX(1.0f);
        passwordLabel.setFont(new Font(passwordLabel.getFont().getName(), Font.BOLD, passwordLabel.getFont().getSize()));
        passwordLabel.setForeground(new Color(-14932698));
        passwordLabel.setHorizontalAlignment(0);
        passwordLabel.setHorizontalTextPosition(0);
        passwordLabel.setIconTextGap(5);
        passwordLabel.setMaximumSize(new Dimension(100000, 50000));
        passwordLabel.setMinimumSize(new Dimension(100, 40));
        passwordLabel.setName("Password");
        passwordLabel.setOpaque(false);
        passwordLabel.setPreferredSize(new Dimension(400, 40));
        passwordLabel.setText("Password");
        Welcome.add(passwordLabel, new CellConstraints(1, 5, 1, 1, CellConstraints.CENTER, CellConstraints.DEFAULT, new Insets(1, 1, 1, 1)));
        insertYourPasswordFormattedTextField = new JFormattedTextField();
        insertYourPasswordFormattedTextField.setAlignmentX(1.0f);
        insertYourPasswordFormattedTextField.setAlignmentY(1.0f);
        insertYourPasswordFormattedTextField.setAutoscrolls(false);
        insertYourPasswordFormattedTextField.setBackground(new Color(-1904654));
        insertYourPasswordFormattedTextField.setCaretColor(new Color(-789517));
        insertYourPasswordFormattedTextField.setDisabledTextColor(new Color(-3946295));
        insertYourPasswordFormattedTextField.setDragEnabled(true);
        insertYourPasswordFormattedTextField.setHorizontalAlignment(0);
        insertYourPasswordFormattedTextField.setInheritsPopupMenu(false);
        insertYourPasswordFormattedTextField.setMargin(new Insets(1, 1, 1, 1));
        insertYourPasswordFormattedTextField.setName("passwordText");
        insertYourPasswordFormattedTextField.setOpaque(true);
        insertYourPasswordFormattedTextField.setPreferredSize(new Dimension(400, 40));
        insertYourPasswordFormattedTextField.setSelectedTextColor(new Color(-3946295));
        insertYourPasswordFormattedTextField.setSelectionColor(new Color(-1904652));
        insertYourPasswordFormattedTextField.setText("insert your password");
        Welcome.add(insertYourPasswordFormattedTextField, new CellConstraints(1, 7, 1, 1, CellConstraints.CENTER, CellConstraints.DEFAULT, new Insets(1, 1, 1, 1)));
        usernameLabel.setNextFocusableComponent(Welcome);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return Welcome;
    }
}
